name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js v18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run validator
        run: npm run validator

      - name: Run formatter
        run: npm run format:check
